#ifndef FIVEFRAMEDIFFMACRO_H
#define FIVEFRAMEDIFFMACRO_H

#define MEDIAN_FILTER_SIZE		3		//中值滤波孔径大小

#define FRAME_DIFF_THRESHOLD_1	8		// 差帧阈值T1

#define FRAME_DIFF_THRESHOLD_2	90		// 8邻域阈值T2

#endif // FIVEFRAMEDIFFMACRO_H
